post http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdvaXN0aW5lbiIsImlkIjoiNjNiN2NjZTRjOWNmMDEyODY5ZmJiZDlkIiwiaWF0IjoxNjcyOTkyNTMzfQ.VyXwNL8Kat9b-Q_rZCM280kyRB06GdJyAI5hZ0tVpac

{
    "title": "Maantiepsyöräily on kivaa",
    "author": "Maantie Pyöräilijä",
    "url": "https://www.canyon.com/"
}